version: 2
jobs:
  build:
    working_directory: ~/hrm-backend
    docker:
      - image: circleci/ruby:2.6.3
        environment:
          PGHOST: localhost
          PGUSER: postgres
          RAILS_ENV: test
      - image: postgres:11
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: hrm-backend_test
          POSTGRES_PASSWORD: ""
    steps:
      - checkout

      # Restore Cached Dependencies
      - type: cache-restore
        name: Restore bundle cache
        key: hrm-backend-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run: bundle install --path vendor/bundle

      # Cache Dependencies
      - type: cache-save
        name: Store bundle cache
        key: hrm-backend-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      # Wait for DB
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m

      # Setup the environment
      - run: cp .env.test .env

      # Setup the database
      - run: bundle exec rake db:setup

      # Run the tests
      - run: bundle exec rspec